development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: bear.avicus.net
  database: steve
  username: steve
  password: YPqbsNwUXFXWF9
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: host
  database: avicus
  username: username
  password: password
